export enum VideoContentStyle {
  Educational = 'Educational',
  Entertainment = 'Entertainment',
  Inspirational = 'Inspirational',
  News = 'News',
  Documentary = 'Documentary',
  Comedy = 'Comedy',
  Tutorial = 'Tutorial',
  Review = 'Review',
  Gaming = 'Gaming',
  Vlog = 'Vlog',
  StoryDriven = 'Story-driven',
  Analysis = 'Analysis',
  BehindTheScenes = 'Behind the Scenes',
  ASMR = 'ASMR',
  Satire = 'Satire',
  Cinematic = 'Cinematic',
  Experimental = 'Experimental',
  Motivational = 'Motivational',
  DarkHumor = 'Dark Humor',
  Explainer = 'Explainer',
  VisualStorytelling = 'Visual Storytelling',
  HorrorNarrative = 'Horror Narrative',
  Philosophical = 'Philosophical',
  TrendAnalysis = 'Trend Analysis',
  TechFuturism = 'Tech Futurism',
  AIGeneratedContent = 'AI-Generated Content',
  Interactive = 'Interactive',
  DataDriven = 'Data-Driven',
  StepByStep = 'Step-by-Step',
  CaseBased = 'Case-Based',
  ProblemSolution = 'Problem-Solution',
  DebateStyle = 'Debate Style',
  InterviewStyle = 'Interview Style',
  WorkshopStyle = 'Workshop Style',
  QuickTips = 'Quick Tips',
  DeepDive = 'Deep Dive'
}

export enum VideoLength {
  ShortsReels = 'shorts/reels',
  UnderFiveMin = 'under 5 min',
  FiveToTenMin = '5-10 min',
  TenToTwentyMin = '10-20 min',
  TwentyPlusMin = '20+ min'
}


export enum ExperienceLevel {
  Beginner = 'beginner',
  Intermediate = 'intermediate',
  Advanced = 'advanced'
}

export enum VideoTargetInterest {
  Tech = 'Tech',
  Fitness = 'Fitness',
  Finance = 'Finance',
  Education = 'Education',
  SelfImprovement = 'Self Improvement',
  Fashion = 'Fashion',
  Cooking = 'Cooking',
  Gaming = 'Gaming',
  Travel = 'Travel',
  Music = 'Music',
  Art = 'Art',
  Entrepreneurship = 'Entrepreneurship',
  Science = 'Science',
  Health = 'Health',
  Automotive = 'Automotive',
  Productivity = 'Productivity',
  Psychology = 'Psychology',
  Sports = 'Sports',
  Parenting = 'Parenting',
  MoviesAndTV = 'Movies & TV',
  History = 'History',
  DIYAndCrafts = 'DIY & Crafts',
  Business = 'Business',
  ASMR = 'ASMR',
  Horror = 'Horror',
  Sustainability = 'Sustainability',
  BlockchainAndCrypto = 'Blockchain & Crypto',
  SpaceAndAstronomy = 'Space & Astronomy',
  PetsAndAnimals = 'Pets & Animals',
  FoodScience = 'Food Science',
  MindfulnessAndMeditation = 'Mindfulness & Meditation',
  MythologyAndFolklore = 'Mythology & Folklore',
  SurvivalAndOutdoors = 'Survival & Outdoors',
  LanguagesAndLinguistics = 'Languages & Linguistics',
  ESports = 'E-Sports',
  TrueCrime = 'True Crime',
  Programming = 'Programming'
}

export enum VideoType {
  Tutorial = 'Tutorial',
  Review = 'Review',
  Reaction = 'Reaction',
  Documentary = 'Documentary',
  Vlog = 'Vlog',
  QAndA = 'Q&A',
  Podcast = 'Podcast',
  LiveStreaming = 'Live Streaming',
  BehindTheScenes = 'Behind the Scenes',
  Challenge = 'Challenge',
  Interview = 'Interview',
  SketchComedy = 'Sketch Comedy',
  Unboxing = 'Unboxing',
  Parody = 'Parody',
  TimeLapse = 'Time-Lapse',
  MiniDocumentary = 'Mini-Documentary',
  TutorialSeries = 'Tutorial Series',
  Experiments = 'Experiments',
  FanTheories = 'Fan Theories',
  Compilation = 'Compilation',
  Storytelling = 'Storytelling',
  AnimatedExplainer = 'Animated Explainer',
  Speedrun = 'Speedrun',
  Comparison = 'Comparison',
  TierList = 'Tier List',
  BehindTheMusic = 'Behind the Music',
  MysteriSolving = 'Mystery Solving',
  ParanormalInvestigation = 'Paranormal Investigation',
  TechBreakdown = 'Tech Breakdown',
  BuildAndCreate = 'Build & Create',
  ProductReview = 'Product Review',
  SoftwareTutorial = 'Software Tutorial',
  CaseStudy = 'Case Study',
  ExpertInterview = 'Expert Interview',
  NewsAnalysis = 'News Analysis',
  HowToGuide = 'How-to Guide',
  IndustryInsights = 'Industry Insights',
  ToolComparison = 'Tool Comparison',
  SuccessStory = 'Success Story',
  Troubleshooting = 'Troubleshooting'
}
